FROM openfoam:10

USER root

# install python
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip

# do some cleaning up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# install python packages
RUN pip3 install numpy
RUN pip3 install matplotlib
RUN pip3 install pandas
RUN pip3 install scipy
RUN pip3 install PyFoam

# for Salome
RUN pip3 install psutil


# switch back to user foam
USER foam
